<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.gj.mall</groupId>
        <artifactId>gj-mall-server</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>gj-mall-order</artifactId>
    <name>gj-mall-order</name>
    <description>订单中心模块</description>
    <dependencies>
        <dependency><groupId>com.gj.mall</groupId><artifactId>gj-mall-framework</artifactId></dependency>
        <dependency><groupId>com.gj.mall</groupId><artifactId>gj-mall-user</artifactId></dependency>
        <dependency><groupId>com.gj.mall</groupId><artifactId>gj-mall-product</artifactId></dependency>
        <dependency><groupId>com.gj.mall</groupId><artifactId>gj-mall-cart</artifactId></dependency>
        <dependency><groupId>com.gj.mall</groupId><artifactId>gj-mall-marketing</artifactId></dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
