<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.gj.mall</groupId>
        <artifactId>gj-mall-server</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>gj-mall-pay</artifactId>
    <name>gj-mall-pay</name>
    <description>支付模块（策略模式：Mock/Wechat/Alipay）</description>
    <dependencies>
        <dependency><groupId>com.gj.mall</groupId><artifactId>gj-mall-framework</artifactId></dependency>
        <dependency><groupId>com.gj.mall</groupId><artifactId>gj-mall-order</artifactId></dependency>
        <dependency>
            <groupId>com.github.wechatpay-apiv3</groupId>
            <artifactId>wechatpay-java</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alipay.sdk</groupId>
            <artifactId>alipay-sdk-java</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
